vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        user_picture:
            uri_prefix: /img/user-pictures
            upload_destination: '%kernel.project_dir%/public/img/user-pictures'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true